[package]
name = "hello-rust-world"
version = "0.0.1"
authors = ["beefbroccoli"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
